# Generated by Django 3.2 on 2021-04-07 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_num', models.CharField(max_length=11)),
                ('the_1st_judge', models.CharField(blank=True, max_length=100)),
                ('the_2nd_judge', models.CharField(blank=True, max_length=100)),
                ('the_3rd_judge', models.CharField(blank=True, max_length=100)),
                ('the_4th_judge', models.CharField(blank=True, max_length=100)),
                ('the_5th_judge', models.CharField(blank=True, max_length=100)),
                ('the_6th_judge', models.CharField(blank=True, max_length=100)),
                ('the_7th_judge', models.CharField(blank=True, max_length=100)),
                ('the_8th_judge', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web02.classinfo')),
            ],
        ),
    ]
